# path:
save_img_path: "./sample_results/t2v-origin/"
pretrained_model_path: "./pretrained/Latte-0"
pretrained: 
model: LatteT2V
video_length: 16
image_size: [512, 512]
# # beta schedule
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"
variance_type: "learned_range"

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed: 1
run_time: 0
guidance_scale: 7.5
sample_method: 'DDIM'
num_sampling_steps: 50
enable_temporal_attentions: True
enable_vae_temporal_decoder: True # use temporal vae decoder from SVD, maybe reduce the video flicker (It's not widely tested)
cache:
text_prompt: [
              "a woman wearing a white dress walking down the street. She is carrying a basket of flowers and appears to be walking towards a store.",
              "a group of people standing on a stage and waving flags in the air. It appears to be a celebration of some sort.",
              "Yellow and black tropical fish dart through the sea.",
              "Sunset over the sea.",
              "a woman wearing a red dress and sunglasses standing in the desert. She is surrounded by rocks and appears to be posing for the camera.",
              "a group of people playing a game of frisbee in a field. They seem to be having fun and enjoying the outdoor activity",
              "a man wearing a hat sitting at a bar and talking into a microphone. He appears to be interviewing someone", 
              "a man wearing a blue jacket and a hooded sweatshirt walking in the snow. He appears to be enjoying the winter weather.",
              "a group of people sitting around a campfire and enjoying a meal together. They seem to be having a good time and enjoying each other's company.",
              "two men standing in a room and talking to each other. One of them is wearing a blue shirt and the other is wearing a white shirt.",
              "a beautiful view of the ocean with waves crashing against the shore. The sky is clear and the sun is shining brightly. There are also some buildings visible in the background.",
              "a beautiful woman wearing a black dress standing in front of a window. She appears to be looking out of the window and appears to be lost in thought.",
              "a beautiful aerial view of the countryside during the fall season. It captures the breathtaking beauty of the changing colors of the trees and the rolling hills in the background.",
              "a narrow alleyway filled with blue buildings. It appears to be a street in the city of Chefchaouen, Morocco."
              ]