# dataset
dataset: "t2v_img"
use_image_num: 4

data_path: ""
pretrained_model_path: "./pretrained/Latte-0"

# save and load
results_dir: "./train_results/skip_joint_train_skip"

pretrained: 
model: LatteT2V_skip
freeze: False
num_frames: 16
video_length: 16
image_size: 512

num_sampling_steps: 250
frame_interval: 4
fixed_spatial: False
attention_bias: True
learn_sigma: True
extras: 78 # [1, 2] 1 unconditional generation, 2 class-conditional generation

# train config:
save_ceph: True # important
learning_rate: 1e-4
ckpt_every: 10000
clip_max_norm: 0.1
start_clip_iter: 0
local_batch_size: 2 # important
max_train_steps: 1000000
global_seed: 3407
num_workers: 16
log_every: 10
lr_warmup_steps: 100
resume_from_checkpoint:
gradient_accumulation_steps: 2
extra_loss_weight: 5e-5
# low VRAM and speed up training
use_compile: False
mixed_precision: True
enable_xformers_memory_efficient_attention: False
gradient_checkpointing: True