# path:
ckpt: 
save_img_path: "./sample_videos/"
pretrained_model_path: "./pretrained/Latte/"

# model config: 
model: Latte-XL/2
num_frames: 16
image_size: 256 # choices=[256, 512]
frame_interval: 3
fixed_spatial: False
attention_bias: True
learn_sigma: True
extras: 2 # [1, 2] 1 unconditional generation, 2 class-conditional generation
num_classes: 101

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed: 2
sample_method: 'ddim'
num_sampling_steps: 50
cfg_scale: 7.0
run_time: 12
num_sample: 2048
sample_names: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
negative_name: 101

# ddp sample config
per_proc_batch_size: 2
num_fvd_samples: 2048