# dataset
dataset: "ucf101_img"

data_path: "/videos/"
frame_data_txt: "UCF101/train_256_list.txt"
frame_data_path: "UCF101/images_256"
pretrained_model_path: "./pretrained/Latte/"

# save and load
results_dir: "./UCF101_joint_train_results"
pretrained: 

# model config: 
model: LatteIMG-skip
num_frames: 16
image_size: 256 # choices=[256, 512]
num_sampling_steps: 250
frame_interval: 3
fixed_spatial: False
attention_bias: True
learn_sigma: True
extras: 2 # [1, 2] 1 unconditional generation, 2 class-conditional generation

# train config:
save_ceph: True # important
use_image_num: 8 # important
learning_rate: 5e-5
ckpt_every: 3000
clip_max_norm: 0.1
start_clip_iter: 10000
local_batch_size: 4 # important
max_train_steps: 100000
global_seed: 3407
num_workers: 8
log_every: 50
lr_warmup_steps: 300
resume_from_checkpoint:
gradient_accumulation_steps: 1 # TODO
num_classes: 101

# low VRAM and speed up training
use_compile: False
mixed_precision: False
enable_xformers_memory_efficient_attention: False
gradient_checkpointing: False